# Generated by Django 3.2.6 on 2021-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserName', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
