# Generated by Django 4.0.3 on 2022-04-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('Name', models.CharField(max_length=64)),
                ('OPSystem', models.IntegerField(default=-1)),
                ('CPUArch', models.CharField(default='', max_length=8)),
                ('OPSystemName', models.CharField(default='', max_length=64)),
                ('IP', models.CharField(max_length=15)),
                ('Password', models.CharField(default='30313233343536373839616263646566', max_length=32)),
                ('RootUsername', models.CharField(default='root', max_length=32)),
                ('RootPassword', models.CharField(default='', max_length=40)),
                ('Type', models.IntegerField()),
                ('Status', models.IntegerField(default=-1)),
                ('LastUpdateTime', models.IntegerField(default=-1)),
                ('TotalMemory', models.BigIntegerField(default=-1)),
                ('Cores', models.IntegerField(default=-1)),
                ('MotherBoardName', models.CharField(default='', max_length=64)),
                ('CPUName', models.CharField(default='', max_length=64)),
                ('UsingMemory', models.IntegerField(default=-1)),
                ('UsingCPU', models.IntegerField(default=-1)),
                ('Version', models.IntegerField(default=-1)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MAC', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoEIDMachine',
            fields=[
                ('Name', models.CharField(max_length=64)),
                ('OPSystem', models.IntegerField(default=-1)),
                ('CPUArch', models.CharField(default='', max_length=8)),
                ('OPSystemName', models.CharField(default='', max_length=64)),
                ('IP', models.CharField(max_length=15)),
                ('Password', models.CharField(default='30313233343536373839616263646566', max_length=32)),
                ('RootUsername', models.CharField(default='root', max_length=32)),
                ('RootPassword', models.CharField(default='', max_length=40)),
                ('Type', models.IntegerField()),
                ('Status', models.IntegerField(default=-1)),
                ('LastUpdateTime', models.IntegerField(default=-1)),
                ('TotalMemory', models.BigIntegerField(default=-1)),
                ('Cores', models.IntegerField(default=-1)),
                ('MotherBoardName', models.CharField(default='', max_length=64)),
                ('CPUName', models.CharField(default='', max_length=64)),
                ('UsingMemory', models.IntegerField(default=-1)),
                ('UsingCPU', models.IntegerField(default=-1)),
                ('Version', models.IntegerField(default=-1)),
                ('MAC', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SateliteInfo',
            fields=[
                ('Name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Value', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TorrentList',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('FileName', models.CharField(default='', max_length=64)),
                ('FileSize', models.BigIntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('AutoSeeding', models.BooleanField(default=False)),
                ('UpdateTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TorrentRunningList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40)),
                ('peer_id', models.CharField(max_length=40)),
                ('IPAndPort', models.CharField(max_length=12)),
                ('left', models.BigIntegerField(default=0)),
                ('Status', models.IntegerField()),
                ('LastUpdateTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerClientList',
            fields=[
                ('peer_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('IPAndPort', models.CharField(max_length=12)),
                ('TotalUploaded', models.IntegerField(default=0)),
                ('TotalDownloaded', models.IntegerField(default=0)),
                ('key', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserName', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
