# Generated by Django 3.2.6 on 2021-08-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=16)),
                ('IP', models.CharField(max_length=15)),
                ('MAC', models.CharField(max_length=12)),
                ('Type', models.IntegerField()),
                ('User', models.CharField(max_length=16)),
                ('LastUpdateTime', models.IntegerField()),
            ],
        ),
    ]
