# Generated by Django 3.2.6 on 2021-08-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0003_machine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='LastUpdateTime',
        ),
    ]
