# Generated by Django 3.2.6 on 2021-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0005_machine_lastupdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentList',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('HasTorrentFile', models.BooleanField()),
                ('IsServerProvidesFiles', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TorrentRunningList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40)),
                ('peer_id', models.CharField(max_length=40)),
                ('IPAndPort', models.CharField(max_length=12)),
                ('left', models.IntegerField()),
                ('Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackerClientList',
            fields=[
                ('peer_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('IPAndPort', models.CharField(max_length=12)),
                ('TotalUploaded', models.IntegerField(default=0)),
                ('TotalDownloaded', models.IntegerField(default=0)),
                ('key', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
