# Generated by Django 3.2.6 on 2021-10-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0006_torrentlist_torrentrunninglist_trackerclientlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='Password',
            field=models.CharField(default='30313233343536373839616263646566', max_length=32),
        ),
    ]
