# Generated by Django 3.2.8 on 2021-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0007_machine_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SateliteInfo',
            fields=[
                ('Name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Value', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='Encoding',
            field=models.CharField(default='UTF-8', max_length=16),
        ),
    ]
