# Generated by Django 3.2.8 on 2021-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0008_auto_20211112_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sateliteinfo',
            name='Value',
            field=models.TextField(max_length=256),
        ),
    ]
