# Generated by Django 3.2.8 on 2021-12-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0009_alter_sateliteinfo_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='Encoding',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='User',
        ),
    ]
