# Generated by Django 3.2.8 on 2021-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0010_auto_20211205_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='OPSystem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='OPSystemName',
            field=models.CharField(default='', max_length=64),
        ),
    ]
