# Generated by Django 3.2.8 on 2021-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0011_auto_20211205_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='Runtime',
            field=models.CharField(default='', max_length=8),
        ),
    ]
