# Generated by Django 3.2.8 on 2021-12-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0012_machine_runtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='Runtime',
            new_name='CPUArch',
        ),
    ]
