# Generated by Django 3.2.8 on 2021-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0013_rename_runtime_machine_cpuarch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='LastUpdateTime',
            field=models.IntegerField(default=0),
        ),
    ]
