# Generated by Django 3.2.8 on 2021-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0014_alter_machine_lastupdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='Name',
            field=models.CharField(max_length=64),
        ),
    ]
