# Generated by Django 3.2.8 on 2021-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0015_alter_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='CPUName',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='Cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='MotherBoardName',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='TotalMemory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='UsingCPU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='UsingMemory',
            field=models.IntegerField(default=0),
        ),
    ]
