# Generated by Django 3.2.8 on 2021-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0016_auto_20211207_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='Version',
            field=models.IntegerField(default=-1),
        ),
    ]
