# Generated by Django 3.2.8 on 2021-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0017_machine_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='TotalMemory',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='UsingMemory',
            field=models.BigIntegerField(default=0),
        ),
    ]
