# Generated by Django 3.2.8 on 2021-12-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDB', '0018_auto_20211207_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='UsingMemory',
            field=models.IntegerField(default=0),
        ),
    ]
